language: java
jdk:
- oraclejdk8
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-kafka-[0-9]+\\.[0-9]+\\.[0-9]+/"
